#!/bin/bash

installDir="/home/greg/cpf-workspace/noelle-install-release"

# Set the command to execute
cmdToExecute="noelle-load -load ${installDir}/lib/Talkdown.so -Talkdown -print-function-trees ${@} -disable-output"
echo $cmdToExecute ;

# Execute the command
eval $cmdToExecute 
